"""Init

Revision ID: 5a5b556f635d
Revises: 
Create Date: 2023-09-08 18:00:26.625875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a5b556f635d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("day_of_born", sa.Date(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(length=350), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_info_day_of_born"), "users_info", ["day_of_born"], unique=False
    )
    op.create_index(op.f("ix_users_info_email"), "users_info", ["email"], unique=True)
    op.create_index(op.f("ix_users_info_id"), "users_info", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_info_last_name"), "users_info", ["last_name"], unique=False
    )
    op.create_index(op.f("ix_users_info_name"), "users_info", ["name"], unique=False)
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users_info.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contacts_id"), "contacts", ["id"], unique=False)
    op.create_index(
        op.f("ix_contacts_phone_number"), "contacts", ["phone_number"], unique=False
    )
    op.create_table(
        "user_m2m_contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users_info.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_m2m_contact")
    op.drop_index(op.f("ix_contacts_phone_number"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_users_info_name"), table_name="users_info")
    op.drop_index(op.f("ix_users_info_last_name"), table_name="users_info")
    op.drop_index(op.f("ix_users_info_id"), table_name="users_info")
    op.drop_index(op.f("ix_users_info_email"), table_name="users_info")
    op.drop_index(op.f("ix_users_info_day_of_born"), table_name="users_info")
    op.drop_table("users_info")
    # ### end Alembic commands ###
